export enum AppRoutes {
  MAIN = 'MAIN',
  PROFILE = 'PROFILE',
  NOT_FOUND = 'NOT_FOUND',
  CREATE_EVENTS = 'CREATE_EVENTS',
  EVENT_DETAIL ='EVENT_DETAIL',
  POST_DETAIL  = 'POST_DETAIL',
  COMMENTS = 'COMMENTS',
  // CHAT_ADMIN= 'CHAT_ADMIN',
  USERS='USERS',
  ORGANIZATION='ORGANIZATION',
  PROGRAM_DETAIL='PROGRAM_DETAIL',
  CAMP_DETAIL='CAMP_DETAIL',
  USER_NOTIFICATION='USER_NOTIFICATION',
  PARTNER_PAGE='PARTNER_PAGE'
}